/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.security.MessageDigest;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class MD5 extends javax.swing.JFrame {

    /**
     * Creates new form MD5
     */
    public MD5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtpw = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtchuoi = new javax.swing.JTextArea();
        btndnhap = new javax.swing.JButton();
        btndangky = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("HASH MD5");

        jLabel2.setText("User name:");

        jLabel3.setText("Password");

        jLabel4.setText("Result 1:");

        jLabel5.setText("Result 2:");

        jLabel6.setText("Chuỗi: Username + pass");

        txtpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwActionPerformed(evt);
            }
        });

        txt2.setColumns(20);
        txt2.setRows(5);
        jScrollPane1.setViewportView(txt2);

        txt1.setColumns(20);
        txt1.setRows(5);
        jScrollPane2.setViewportView(txt1);

        txtchuoi.setColumns(20);
        txtchuoi.setRows(5);
        jScrollPane3.setViewportView(txtchuoi);

        btndnhap.setText("đăng nhập");
        btndnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndnhapActionPerformed(evt);
            }
        });

        btndangky.setText("đăng ký");
        btndangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangkyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel1)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpw, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btndnhap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btndangky))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addComponent(txtname))))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel5)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndnhap)
                    .addComponent(btndangky))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpwActionPerformed

    private void btndangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangkyActionPerformed
        try{
            
        String user=txtname.getText();
        String pass=txtpw.getText();
        String bam="";
        bam=user+pass;
        MessageDigest md= MessageDigest.getInstance("MD5");
        md.update(bam.getBytes());
        byte[] byteData =md.digest();
        StringBuffer sb=new StringBuffer();
        for(int i=0;i<byteData.length;i++){
            sb.append(Integer.toString((byteData[i]&0xff)+0x100,16).substring(1));
        }
        System.err.println("digest (in hex format)::"+sb.toString());
        txt1.setText(sb.toString());
        StringBuffer hexString =new StringBuffer();
        for(int i=0;i<byteData.length;i++){
            String hex =Integer.toHexString(0xff&byteData[i]);
            if(hex.length()==1){
                hexString.append('0');
            }
            hexString.append(hex);
        }
        System.out.println("digest(in hex format)::"+hexString.toString());
        txt2.setText(hexString.toString());
        txtchuoi.setText(bam.toString());
        BufferedWriter bw=null;
        String filename="F:\\BamMD5.txt";
        bw =new BufferedWriter(new FileWriter(filename));
        bw.write(hexString.toString());
        bw.close();
        JOptionPane.showMessageDialog(null, "ban dang ky thanh cong vui long dang nhap lai");
        }
        catch(Exception ex){
        System.err.println("loi bam user name va pass :"+ex);
    }
        
    
    }//GEN-LAST:event_btndangkyActionPerformed

    private void btndnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndnhapActionPerformed
        String user= txtname.getText();
        String pass=txtpw.getText();
        String bam="";
        bam=user +pass;
        BufferedReader br=null;
        String filename="F:\\BamMD5.txt";
        try{
            br= new BufferedReader(new FileReader(filename));
            StringBuffer sb =new StringBuffer();
            char[] ca =new char[5];
            while (br.ready()){
                int len=br.read(ca);
                sb.append(ca,0,len);
                

            }
            br.close();
            System.out.println("chung thuc"+""+sb);
            String chuoi=sb.toString();
            MessageDigest md= MessageDigest.getInstance("MD5");
            md.update(bam.getBytes());
            byte[] byteData=md.digest();
            StringBuffer hexString=new StringBuffer();
            for(int i=0;i<byteData.length;i++){
                String hex=Integer.toHexString(0xff&byteData[i]);
                if (hex.length()==1) {
                    hexString.append('0');
                    
                }
                hexString.append(hex);
            }
                System.out.println("bam user va pass"+""+hexString.toString()); 
                Boolean k=hexString.toString().equals(chuoi);
                if(k==true){
                    JOptionPane.showConfirmDialog(null, "dang nhap thanh cong");
                    txt1.setText(hexString.toString());
                    txt2.setText("username "+user+""+"password:"+pass);
                    
                }
                else
                    JOptionPane.showConfirmDialog(null, "dang nhap that bai");
            
            
        }catch(Exception ex){
                    System.out.println("loi dang nhap"+ex);
                    }
        
    }//GEN-LAST:event_btndnhapActionPerformed
    
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MD5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangky;
    private javax.swing.JButton btndnhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txt1;
    private javax.swing.JTextArea txt2;
    private javax.swing.JTextArea txtchuoi;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpw;
    // End of variables declaration//GEN-END:variables
}
